# syntax=docker/dockerfile:1
# ARENA environment for RunPod (and local testing).
#
# No CUDA toolkit in the base image on purpose: PyTorch and JAX ship their own CUDA
# libraries as pip packages. The only thing that has to match is the host's NVIDIA
# driver, which is checked by smoke_test.py.

FROM ubuntu:24.04

# cu126 = CUDA 12.6: works with NVIDIA driver >= 525, same CUDA major as JAX's cuda12 build,
#         and covers every card ARENA needs (RTX 20/30/40, A4000/A5000, A100, H100).
#         Does NOT support RTX 50-series or B200.
# cu130 = CUDA 13.0: PyTorch's current default. Needs driver >= 580. Turing (RTX 20) and newer.
ARG TORCH_BACKEND=cu126
ARG PYTHON_VERSION=3.11

ENV DEBIAN_FRONTEND=noninteractive \
    VIRTUAL_ENV=/opt/venv \
    PATH=/opt/venv/bin:$PATH \
    UV_LINK_MODE=copy \
    # JAX grabs 75% of GPU memory on import by default, which starves PyTorch.
    XLA_PYTHON_CLIENT_PREALLOCATE=false \
    # Headless MuJoCo rendering (ARENA 2.3).
    MUJOCO_GL=osmesa \
    PYOPENGL_PLATFORM=osmesa

# build-essential: Triton (torch.compile) needs a C compiler at runtime.
RUN apt-get update && apt-get install -y --no-install-recommends \
        git curl ca-certificates openssh-server build-essential \
        libosmesa6 libgl1 libglib2.0-0t64 ffmpeg tmux htop nano \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /run/sshd

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

RUN uv python install ${PYTHON_VERSION} && uv venv --python ${PYTHON_VERSION} /opt/venv

WORKDIR /opt/arena-image
COPY requirements.in overrides.txt requirements.lock* ./

# Two modes:
#  - no requirements.lock: resolve fresh from requirements.in, then freeze the result
#    to /opt/arena-image/requirements.lock (copy it out and commit it — see README).
#  - requirements.lock present: install exactly those versions, no re-resolution.
RUN --mount=type=cache,target=/root/.cache/uv \
    if [ -s requirements.lock ]; then \
        echo ">>> Installing pinned versions from requirements.lock" && \
        uv pip install --no-deps --torch-backend ${TORCH_BACKEND} -r requirements.lock ; \
    else \
        echo ">>> No lock file: resolving fresh from requirements.in" && \
        uv pip install --torch-backend ${TORCH_BACKEND} --override overrides.txt -r requirements.in && \
        { echo "# Generated by 'docker build' with TORCH_BACKEND=${TORCH_BACKEND}, $(date -u +%F)"; \
          uv pip freeze; } > requirements.lock ; \
    fi \
    && echo "${TORCH_BACKEND}" > torch_backend.txt

COPY smoke_test.py start.sh arena-session.sh ./
RUN chmod +x start.sh arena-session.sh smoke_test.py \
    && ln -s /opt/arena-image/arena-session.sh /usr/local/bin/arena-session \
    && ln -s /opt/arena-image/smoke_test.py /usr/local/bin/smoke-test \
    # SSH sessions don't inherit Docker ENV, so repeat the important bits for login shells.
    && printf '%s\n' \
        'export VIRTUAL_ENV=/opt/venv' \
        'export PATH=/opt/venv/bin:$PATH' \
        'export XLA_PYTHON_CLIENT_PREALLOCATE=false' \
        'export MUJOCO_GL=osmesa PYOPENGL_PLATFORM=osmesa' \
        > /etc/profile.d/10-arena.sh

WORKDIR /root
EXPOSE 22
CMD ["/opt/arena-image/start.sh"]
